@BaseApi = http://localhost:5001/api
@Username = test
@Password = 111111
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjEiLCJuYmYiOjE1ODQ1MDM1MzQsImV4cCI6MTU4NTEwODMzNCwiaWF0IjoxNTg0NTAzNTM0fQ.GTBBYmoW0pJEC8G4Mjy316QAKpyq5J4KBEfQ2UBkHH4


### register
POST {{BaseApi}}/user/register HTTP/1.1
content-type: application/json

{
    "username": "{{Username}}",
    "password": "{{Password}}"
}

### login
POST {{BaseApi}}/user/login HTTP/1.1
content-type: application/json

{
    "username": "{{Username}}",
    "password": "{{Password}}"
}

### user profile
GET {{BaseApi}}/user/profile HTTP/1.1
content-type: application/json
Authorization: Bearer {{Token}}


### product list
GET {{BaseApi}}/product/list/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{Token}}

### product detail
GET {{BaseApi}}/product/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{Token}}

### product not found
GET {{BaseApi}}/product/99 HTTP/1.1
content-type: application/json
Authorization: Bearer {{Token}}


### page content
GET {{BaseApi}}/page/tag/home HTTP/1.1
